version: '3.7'
services:
  web:
    container_name: enterprise-angular-starter
    build: .
    context: .
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
